version:  '3.7'
services:
#    mariadb:
#        image: mariadb:10.5.3
#        container_name: zzoo-mariadb
#        volumes:
#            - mariadb_zzoo_api:/var/lib/mysql
#        environment:
#            - MYSQL_ROOT_PASSWORD=pasaia
#            - MYSQL_DATABASE=zzoo
#            - MYSQL_USER=pasaia
#            - MYSQL_PASSWORD=pasaia
#        ports:
#            - "3306:3306"

    php:
        container_name: zzoo-php
        env_file: ./.env
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - DOCKER_TIMEZONE=${DOCKER_TIMEZONE}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
        restart: always
#        depends_on:
#            - mariadb
        external_links:
          - zergaordenantzak-mariadb
        volumes:
            - '.:/usr/src/app'
        user: 1000:1000
        environment:
            - APP_ENV=dev
            - PHP_IDE_CONFIG=serverName=zergaordenantzak.test
            - XDEBUG_CONFIG=remote_host=192.168.2.8
        networks:
            - zergaordenantzak_zzoo

    nginx:
        container_name: zzoo-nginx
        image: nginx:1.15.3-alpine
        restart: always
        volumes:
            - '.:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        depends_on:
            - php
        ports:
            - 8080:80
        networks:
            - zergaordenantzak_zzoo

volumes:
    mariadb_zzoo_api:

networks:
    zergaordenantzak_zzoo:
        external: true
